#include "common.h"

namespace aoc_2018_14 {

/// Compute the prefix sum of a vector of 8-bit integers.
template <typename D>
hn::Vec<D> prefix_sum_u8(D d, const hn::Vec<D> v)
    requires(std::same_as<hn::TFromD<D>, uint8_t>)
{
    static_assert(hn::Lanes(D()) <= 64);
    using D64 = hn::Repartition<uint64_t, D>;

    // Compute prefix sum of each group of 8 elements:
    hn::Vec<D64> v64 = hn::BitCast(D64(), v);
    v64 += hn::ShiftLeft<8>(v64);
    v64 += hn::ShiftLeft<16>(v64);
    v64 += hn::ShiftLeft<32>(v64);

    const hn::Vec<D> v8 = hn::BitCast(d, v64);

    // Compute prefix sum for full 128-bit blocks.
    HWY_ALIGN_MAX static constexpr uint8_t shuf8_to_16[64] = {
        0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, // --> zero
        7,    7,    7,    7,    7,    7,    7,    7,
        0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, // --> zero
        7,    7,    7,    7,    7,    7,    7,    7,
        0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, // --> zero
        7,    7,    7,    7,    7,    7,    7,    7,
        0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, // --> zero
        7,    7,    7,    7,    7,    7,    7,    7,
    };
    const hn::Vec<D> v8k = hn::TableLookupBytesOr0(v8, hn::Load(d, shuf8_to_16));
    const hn::Vec<D> v16 = v8 + v8k;

    // Compute prefix sum for 256-bit blocks.
    const hn::Vec<D> v16k = hn::Set(d, hn::ExtractLane(v16, 15));
    const hn::Vec<D> v32 = hn::MaskedAddOr(v16, hn::Not(hn::FirstN(d, 16)), v16, v16k);

    if constexpr (hn::Lanes(D()) <= 32) {
        return v32;
    } else {
        // Compute prefix sum for 512-bit blocks.
        const hn::Vec<D> v64_0 = hn::MaskedAddOr(v32, hn::Not(hn::FirstN(d, 32)), v32,
                                                 hn::Set(d, hn::ExtractLane(v16, 31)));
        const hn::Vec<D> v64_1 = hn::MaskedAddOr(v64_0, hn::Not(hn::FirstN(d, 48)), v64_0,
                                                 hn::Set(d, hn::ExtractLane(v16, 47)));
        return v64_1;
    }
}

void run(std::string_view buf)
{
    auto [n] = find_numbers_n<size_t, 1>(buf);

    using D = hn::ScalableTag<uint8_t>;
    constexpr D d;

    inplace_vector<uint8_t, 20> needle;
    for (auto k = n; k; k /= 10)
        needle.unchecked_push_back(k % 10);
    std::ranges::reverse(needle);

    // All credits go to u/askalski for the algorithm used here:
    // <https://old.reddit.com/r/adventofcode/comments/a6wpwa/2018_day_14_breaking_the_1_billion_recipes_per>
    //
    // This exploits the fact that the sequences generated by any of the 10
    // possible starting offsets eventually merge into a common subsequence of
    // the full sequence, starting at index 23.
    constexpr size_t common_subseq_start = 23;

    // Pre-defined maximum size because I'm lazy. This works for my input.
    constexpr size_t buffer_size = 30'000'000;
    auto storage = std::make_unique_for_overwrite<uint8_t[]>(2 * buffer_size);
    uint8_t *full_subseq = storage.get();
    uint8_t *common_subseq = storage.get() + buffer_size;

    // Pre-fill the full sequence with 1s; this avoids two individual writes
    // per element with two-digit sums since the tens digit is always 1, which
    // simplifies step_interior_simd().
    memset(full_subseq, 1, buffer_size);
    full_subseq[0] = 3;
    full_subseq[1] = 7;

    uint8_t *fullp = full_subseq + 2;
    uint8_t *prev_fullp;
    uint8_t *commonp = common_subseq;

    size_t f0 = 0, f1 = 1;  // indices into the full sequence
    ssize_t c0 = 0, c1 = 0; // indices into the common subsequence
    size_t next = common_subseq_start;

    // Advances by a single step, generating one or two new elements into the
    // full sequence.
    auto step_single = [&] {
        const int sum = full_subseq[f0] + full_subseq[f1];
        fullp += sum >= 10;
        *fullp++ = sum >= 10 ? sum - 10 : sum;

        const size_t new_size = fullp - full_subseq;
        if (next < new_size) {
            *commonp++ = full_subseq[next];
            next += full_subseq[next] + 1;
        }

        c0 = f0 >= common_subseq_start ? c0 + 1 : 0;
        c1 = f1 >= common_subseq_start ? c1 + 1 : 0;
        f0 = (f0 + 1 + full_subseq[f0]) % new_size;
        f1 = (f1 + 1 + full_subseq[f1]) % new_size;
    };

    // Advances by a SIMD register's worth of steps, generating between N and
    // 2N new elements into the full sequence, where N is the number of SIMD
    // lanes.
    auto step_interior_simd = [&] {
        const hn::Vec<D> a = hn::LoadU(d, &common_subseq[c0]);
        const hn::Vec<D> b = hn::LoadU(d, &common_subseq[c1]);
        const hn::Vec<D> sum = a + b;

        const hn::Vec<D> ten = hn::Set(d, 10);
        const hn::Mask<D> ge10 = hn::Ge(sum, ten);
        const hn::Vec<D> lengths = hn::IfThenElse(ge10, hn::Set(d, 2), hn::Set(d, 1));
        const hn::Vec<D> length_prefix_sum = prefix_sum_u8(d, lengths);

        HWY_ALIGN_MAX std::array<uint8_t, hn::MaxLanes(d)> last_digit;
        hn::Store(hn::MaskedSubOr(sum, ge10, sum, ten), d, last_digit.data());

        HWY_ALIGN_MAX std::array<uint8_t, hn::MaxLanes(d)> offsets;
        hn::Store(length_prefix_sum - hn::Set(d, 1), d, offsets.data());

        // Scatter the results to the output buffer. Only the last digits
        // matter here since the output buffer has been pre-filled with 1s.
        for (size_t i = 0; i < hn::Lanes(d); i++)
            fullp[offsets[i]] = last_digit[i];

        fullp += offsets.back() + 1zu;

        while (full_subseq + next < fullp) {
            *commonp++ = full_subseq[next];
            next += full_subseq[next] + 1;
        }

        // Naively using ReduceSum() here risks overflowing the 8-bit elements
        // for ≥256-bit vectors. Use SumsOf8 (i.e. vpsadbw on x86-64) to
        // sidestep this by reducing 8-element groups to 64-bit sums first.
        constexpr hn::RepartitionToWideX3<D> w;
        f0 += hn::ReduceSum(w, hn::SumsOf8(a)) + hn::Lanes(d);
        f1 += hn::ReduceSum(w, hn::SumsOf8(b)) + hn::Lanes(d);
        c0 += hn::Lanes(d);
        c1 += hn::Lanes(d);
    };

    auto search = [&](const uint8_t *begin, const uint8_t *end) {
        const void *p = memmem(begin, end - begin, needle.data(), needle.size());
        if (!p) [[likely]]
            return false;

        fmt::print("{}\n", fmt::join(std::span(full_subseq + n, 10), ""));
        fmt::print("{}\n", static_cast<const uint8_t *>(p) - full_subseq);
        return true;
    };

    do {
        constexpr int chunk_size_approx = 100'000;
        prev_fullp = fullp;

        // Phase 1: One or both elves are within a unique prefix. Proceed one
        // step at a time until they are both in the common subsequence.
        while (std::min(f0, f1) < common_subseq_start)
            step_single();

        // Phase 2: when both elves are in the interior of common subsequence,
        // meaning that we have enough elements to fill a SIMD register, use
        // SIMD to generate a chunk of new elements at a time.
        //
        // Limit the number of steps we take here; if we process the entire
        // sequence each time, the sequence grows geometrically, risking
        // overshooting by a lot which wastes time in the substring search for
        // part 2.
        while (fullp - prev_fullp < chunk_size_approx &&
               common_subseq + std::max(c0, c1) + hn::Lanes(d) - 1 < commonp)
            step_interior_simd();

        // Phase 3: one or both elves might not have enough elements left in
        // the common subsequence to fill a complete SIMD register, and will
        // wrap around to the beginning shortly if so. Do one step at a time
        // until they wrap around to the beginning, which brings us back to
        // phase 1.
        while (common_subseq + std::max(c0, c1) + hn::Lanes(d) - 1 >= commonp)
            step_single();
    } while (prev_fullp < full_subseq + n + 10 || !search(prev_fullp - 10, fullp));
}

}
